server:
  port: 8081

spring:
  application:
    name: java-ai-engineering-specialization

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

rag:
  chat:
    base-url: http://localhost:11434
    model-name: llama3.2:1b
    temperature: 0.2
    timeout: 60s
  chunking:
    max-segment-size: 300
    max-overlap-size: 30
  embedding:
    base-url: http://localhost:11434
    model-name: nomic-embed-text
    timeout: 60s
  retrieval:
    max-results: 3
    min-score: 0.0
