server:
  port: 8080

spring:
  application:
    name: java-ai-engineering-specialization

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

rag:
  chunking:
    max-segment-size: 300
    max-overlap-size: 30
  embedding:
    base-url: http://localhost:11434
    model-name: nomic-embed-text
    timeout: 60s
  retrieval:
    max-results: 3
    min-score: 0.0
